# Generated by Django 3.2.8 on 2022-01-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastedata',
            name='weight',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=15),
        ),
    ]
