# Generated by Django 3.2.8 on 2022-01-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_manager', '0002_alter_wastedata_weight'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wastedata',
            name='no_duplicate_waste_data',
        ),
        migrations.AddConstraint(
            model_name='wastedata',
            constraint=models.UniqueConstraint(fields=('facility', 'pickup_date', 'waste_name', 'is_recycled'), name='no_duplicate_waste_data'),
        ),
    ]
