# Generated by Django 3.2.8 on 2022-01-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_manager', '0003_auto_20220118_1408'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wastedata',
            name='no_duplicate_waste_data',
        ),
        migrations.AddConstraint(
            model_name='wastedata',
            constraint=models.UniqueConstraint(fields=('facility', 'pickup_date', 'waste_name', 'waste_category', 'is_recycled'), name='no_duplicate_waste_data'),
        ),
    ]
