# Generated by Django 3.2.8 on 2022-03-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_manager', '0004_auto_20220119_2121'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wastedata',
            name='no_duplicate_waste_data',
        ),
        migrations.AddField(
            model_name='wastedata',
            name='is_diverted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wastedata',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='wastedata',
            constraint=models.UniqueConstraint(fields=('facility', 'pickup_date', 'waste_name', 'waste_category', 'is_recycled', 'is_diverted'), name='no_duplicate_waste_data'),
        ),
    ]
