# Generated by Django 3.2.8 on 2022-01-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Renewables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('purchased_energy', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('emission_reduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('division', models.CharField(choices=[('retail', 'Retail'), ('professional', 'professional')], max_length=25)),
                ('buyer', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Renewable Energy',
            },
        ),
        migrations.AddConstraint(
            model_name='renewables',
            constraint=models.UniqueConstraint(fields=('year', 'purchased_energy', 'division', 'buyer'), name='no_duplicate_renewable_data'),
        ),
    ]
