# Generated by Django 3.2.8 on 2022-01-16 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_preauthorizeduser_customer'),
        ('staples_ca_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewables',
            name='division',
            field=models.CharField(choices=[('retail', 'retail'), ('professional', 'professional')], max_length=25),
        ),
        migrations.CreateModel(
            name='LedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retrofit_date', models.DateField()),
                ('vendor', models.CharField(max_length=255)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.facility')),
            ],
        ),
    ]
