# Generated by Django 3.2.8 on 2022-02-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staples_ca_dashboard', '0002_auto_20220116_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=255)),
                ('audit_date', models.DateField(blank=True, null=True)),
                ('issue', models.TextField(blank=True, null=True)),
                ('funds_recovered', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_avoidance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
