# Generated by Django 3.2.8 on 2022-02-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staples_ca_dashboard', '0003_billaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='billaudit',
            name='closure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
