# Generated by Django 3.2.8 on 2022-03-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
