# Generated by Django 3.2.8 on 2021-10-13 19:38

import core.storages_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=50, unique=True)),
                ('logo', models.FileField(blank=True, null=True, storage=core.storages_backends.Logos(), upload_to='')),
                ('customer', models.ForeignKey(blank=True, db_column='customer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', to_field='customer_name')),
            ],
            options={
                'verbose_name_plural': 'Divisions',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_identifier', models.CharField(max_length=50, unique=True)),
                ('facility_name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('division', models.ForeignKey(db_column='division', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_to_division', to='core.division', to_field='division_name')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('ALL', 'ALL'), ('RESTRICTED', 'RESTRICTED')], default='RESTRICTED', max_length=10)),
                ('access_division_energy', models.BooleanField(default=False)),
                ('access_division_project', models.BooleanField(default=False)),
                ('access_facility_energy', models.BooleanField(default=False)),
                ('access_facility_project', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, db_column='customer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', to_field='customer_name')),
                ('user', models.OneToOneField(db_column='user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_info', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name_plural': 'User Info',
            },
        ),
        migrations.CreateModel(
            name='FacilityAccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.ForeignKey(blank=True, db_column='facility', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.facility', to_field='facility_identifier')),
                ('user', models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_access_control', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.AddConstraint(
            model_name='facilityaccesscontrol',
            constraint=models.UniqueConstraint(fields=('user', 'facility'), name='NoDup_user_facility'),
        ),
    ]
