# Generated by Django 3.2.8 on 2021-10-14 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_identifier',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='facilityaccesscontrol',
            name='facility',
            field=models.ForeignKey(blank=True, db_column='facility', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.facility', to_field='facility_name'),
        ),
    ]
