# Generated by Django 3.2.8 on 2021-10-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211014_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='facility',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='facility',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
