# Generated by Django 3.2.8 on 2021-10-22 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211022_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='area',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
