# Generated by Django 3.2.8 on 2022-01-10 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userinfo_access_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreAuthorizedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(blank=True, db_column='customer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', to_field='customer_name')),
            ],
        ),
    ]
