# Generated by Django 3.2.8 on 2022-01-14 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_preauthorizeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preauthorizeduser',
            name='customer',
            field=models.ForeignKey(db_column='customer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', to_field='customer_name'),
        ),
    ]
