# Generated by Django 3.2.8 on 2021-10-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_facility_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='category_type',
            field=models.CharField(choices=[('Retail', 'Retail'), ('Warehouse', 'Warehouse')], default='Retail', max_length=15),
        ),
    ]
