# Generated by Django 3.2.8 on 2021-10-23 02:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_facility_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
