# Generated by Django 3.2.8 on 2022-01-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_preauthorizeduser_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_identifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
