# Generated by Django 3.2.8 on 2022-01-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_facility_facility_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='is_investigator',
            field=models.BooleanField(default=False),
        ),
    ]
