# Generated by Django 3.2.8 on 2021-10-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userinfo_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
