# Generated by Django 3.2.8 on 2022-02-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userinfo_is_investigator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='access_investigation',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='is_investigation_manager',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='is_investigator',
        ),
    ]
