# Generated by Django 3.2.8 on 2022-02-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220203_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='preauthorizeduser',
            name='cs_staples_ca_ds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='cs_staples_ca_ds',
            field=models.BooleanField(default=False),
        ),
    ]
