# Generated by Django 3.2.8 on 2021-10-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userinfo_confirmed_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='access_investigation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_investigation_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_investigator',
            field=models.BooleanField(default=True),
        ),
    ]
