# Generated by Django 3.2.8 on 2021-11-01 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_userinfo_access_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_date', models.DateField()),
                ('utility_type', models.CharField(choices=[('Electricity', 'Electricity'), ('NaturalGas', 'NaturalGas'), ('Water', 'Water')], max_length=15)),
                ('usage', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('billing_days', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('facility', models.ForeignKey(db_column='facility', on_delete=django.db.models.deletion.CASCADE, to='core.facility', to_field='facility_name')),
            ],
            options={
                'verbose_name_plural': 'Utility Manager',
            },
        ),
        migrations.AddConstraint(
            model_name='utilitybill',
            constraint=models.UniqueConstraint(fields=('facility', 'billing_date', 'utility_type'), name='no_duplicate_utility_data'),
        ),
    ]
