# Generated by Django 3.2.8 on 2021-11-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('pk_id', models.AutoField(db_column='pk', primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hdd', models.FloatField()),
                ('cdd', models.FloatField()),
            ],
            options={
                'db_table': 'weatherdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('pk_id', models.AutoField(db_column='pk', primary_key=True, serialize=False)),
                ('climate_id', models.CharField(max_length=255, unique=True)),
                ('station_name', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'weatherstation',
                'managed': False,
            },
        ),
    ]
