# Generated by Django 3.2.8 on 2022-01-30 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_alter_userinfo_is_investigator'),
    ]

    operations = [
        migrations.CreateModel(
            name='HC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_increase', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('cost_increase', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(db_column='facility', on_delete=django.db.models.deletion.CASCADE, to='core.facility', to_field='facility_name')),
            ],
        ),
    ]
