# Generated by Django 3.2.8 on 2022-01-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_consumptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hc',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
