# Generated by Django 3.2.8 on 2022-02-22 01:06

import apps.high_consumptions.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_consumptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hc',
            name='hc_document',
            field=models.FileField(blank=True, null=True, storage=apps.high_consumptions.storages_backends.HCDocs(), upload_to=''),
        ),
    ]
