# Generated by Django 3.2.8 on 2022-01-30 16:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('high_consumptions', '0002_hc_target_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hc',
            name='hc_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
