# Generated by Django 3.2.8 on 2022-02-22 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220205_2044'),
        ('high_consumptions', '0002_hc_hc_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='HCReportTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hc_report_id', models.CharField(max_length=255, unique=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, db_column='creator', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hc_report_tracker_creator', to='core.userinfo', to_field='user_unique_id')),
            ],
        ),
    ]
