# Generated by Django 3.2.8 on 2022-03-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_consumptions', '0003_hcreporttracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hc',
            name='cost_increase',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hc',
            name='usage_increase',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
