# Generated by Django 3.2.8 on 2022-01-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_consumptions', '0004_auto_20220131_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='hc',
            name='utility_type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
