# Generated by Django 3.2.8 on 2022-03-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_consumptions', '0004_auto_20220308_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='hcreporttracker',
            name='report_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
