# Generated by Django 3.2.8 on 2021-10-28 16:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('investigation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investigation_date', models.DateField()),
                ('investigation_type', models.CharField(choices=[('HC_WT', 'HC_WT'), ('HC_GAS', 'HC_GAS'), ('HC_EL', 'HC_EL')], max_length=6)),
                ('investigation_description', models.TextField(blank=True, null=True)),
                ('investigation_result', models.TextField(blank=True, null=True)),
                ('in_approval', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('facility', models.ForeignKey(blank=True, db_column='facility', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.facility', to_field='facility_name')),
                ('investigation_creator', models.ForeignKey(blank=True, db_column='investigation_creator', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='investigation_creator', to='core.userinfo', to_field='user_name')),
                ('investigation_investigator', models.ForeignKey(blank=True, db_column='investigation_investigator', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='investigation_investigator', to='core.userinfo', to_field='user_name')),
            ],
        ),
        migrations.AddConstraint(
            model_name='investigation',
            constraint=models.UniqueConstraint(fields=('facility', 'investigation_type', 'investigation_date'), name='no_duplicate_investigations'),
        ),
    ]
