# Generated by Django 3.2.8 on 2021-10-25 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigation',
            name='investigator',
        ),
        migrations.AddField(
            model_name='investigation',
            name='investigation_investigator',
            field=models.ForeignKey(blank=True, db_column='investigation_investigator', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='investigation_investigator', to='core.userinfo', to_field='user_name'),
        ),
    ]
