# Generated by Django 3.2.8 on 2021-11-05 03:39

import apps.investigations.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='investigation_document',
            field=models.FileField(blank=True, null=True, storage=apps.investigations.storages_backends.InvestigationDocs(), upload_to=''),
        ),
    ]
