# Generated by Django 3.2.8 on 2021-10-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0002_auto_20211025_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investigation',
            name='in_approval',
            field=models.BooleanField(default=False),
        ),
    ]
