# Generated by Django 3.2.8 on 2022-02-03 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userinfo_is_investigator'),
        ('investigations', '0002_investigation_investigation_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_investigation', models.BooleanField(default=False)),
                ('is_investigator', models.BooleanField(default=False)),
                ('is_investigation_manager', models.BooleanField(default=False)),
                ('user_info', models.OneToOneField(db_column='user_info', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigation_authorization', to='core.userinfo', to_field='user_unique_id')),
            ],
        ),
    ]
