# Generated by Django 3.2.8 on 2021-10-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0003_auto_20211025_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investigation',
            options={'verbose_name_plural': 'Utility Usage'},
        ),
        migrations.AddConstraint(
            model_name='investigation',
            constraint=models.UniqueConstraint(fields=('facility', 'investigation_type', 'investigation_date'), name='no_duplicate_investigations'),
        ),
    ]
