# Generated by Django 3.2.8 on 2022-03-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0004_investigation_investigation_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='investigation_bas_fix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='require_bas_fix',
            field=models.BooleanField(default=False),
        ),
    ]
