# Generated by Django 3.2.8 on 2021-11-25 01:51

import apps.reports.storages_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('log_name', models.CharField(max_length=255)),
                ('log_description', models.TextField(blank=True, null=True)),
                ('log_file', models.FileField(blank=True, null=True, storage=apps.reports.storages_backends.LogsDocs(), upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('report_name', models.CharField(max_length=255)),
                ('report_description', models.TextField(blank=True, null=True)),
                ('report_file', models.FileField(blank=True, null=True, storage=apps.reports.storages_backends.ReportsDocs(), upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_report', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
